### ISSUE TITLE
Why was dgraph not included?

### ISSUE THREAD

**Issue by lrrountr** [tigergraph/graph-database-benchmark#3]
Not an issue, just curiosity on why dgraph was not included in this database benchmark, I really like the outputs provided here for comparison purposes...

**Comment by mingxiw** [comment]
we benchmarked those that we consider relative mature and competitive. However, as so many graph database vendor entered this space, there is no way we can exhaust all the benchmark. However, we open sourced our benchmark code and anyone is welcomed to reproduce the results. And we are welcoming any contribution from the open source community to add more vendor results.
